package excpack;

/**
 * Created by Оксана on 16.12.2016.
 */

//An exception can be generated by one method and caught by another.
   class ExcTest{
    //Generate an exception.
    static void genException(){
        int nums[]=new int[4];

        System.out.println("Before exception is generated.");

        //Generate an index out-of-bounds exception.
        nums[7] = 10; //Exception generated here.
        System.out.println("this won't be displayed");
    }
}


public class ExcDemo2 {
    public static void main(String[] args) {
        try {
            ExcTest.genException();
        } catch (ArrayIndexOutOfBoundsException exc) {//Exception caught here.
            //catch the exception
            System.out.println("Index out-of-bounds!");
        }
        System.out.println("After catch statement.");
    }
}
